// Loadings
export const LOADING = 'LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

// Loading Indicator
export const LOADING_INDICATOR_START = 'LOADING_INDICATOR_START';
export const LOADING_INDICATOR_SET_PERCENT = 'LOADING_INDICATOR_SET_PERCENT';

export const SUBMIT_FINANCE_DRIVER_SHORT = 'SUBMIT_FINANCE_DRIVER_SHORT';
