export const APPLICANT_SET_NAME = 'APPLICANT_SET_NAME';
export const APPLICANT_SET_CONTACT = 'APPLICANT_SET_CONTACT';
export const APPLICANT_SET_ADDRESS = 'APPLICANT_SET_ADDRESS';
export const APPLICANT_SET_PII = 'APPLICANT_SET_PII';
export const APPLICANT_SET_EMPLOYMENT = 'APPLICANT_SET_EMPLOYMENT';
